export const requiredPermissions = [
  "tabs",
  "activeTab",
  "storage",
  "scripting",
  "alarms",
  "bookmarks",
  "contextMenus",
  "cookies",
  "declarativeNetRequest",
  "declarativeNetRequestFeedback",
  "downloads",
  "history",
  "identity",
  "notifications",
  "offscreen",
  "sidePanel",
  "tabGroups",
  "unlimitedStorage",
  "webNavigation",
  "webRequest",
] as const;
